ProyectoBiblioteca/Models/Autor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoBiblioteca.Models
{
    public class Autor
    {
        public int IdAutor { get; set; }
        public string Descripcion { get; set; }
    }
}

ProyectoBiblioteca/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoBiblioteca.Models
{
    public class Libro
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        
        public Autor oAutor { get; set; }

    }
}

ProyectoBiblioteca/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoBiblioteca.Models
{
    public class Persona
    {
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public string Codigo { get; set; }
        public TipoPersona oTipoPersona { get; set; }
        public bool Estado { get; set; }
    }
}

ProyectoBiblioteca/Models/TipoPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoBiblioteca.Models
{
    public class TipoPersona
    {
        public int IdTipoPersona { get; set; }
        public string Descripcion { get; set; }

    }
}

ProyectoBiblioteca/Controllers/AdminController.cs
using ProyectoBiblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoBiblioteca.Controllers
{
    public class AdminController : Controller
    {
        private static Persona oPesona;
        // GET: Admin
        public ActionResult Index()
        {
            if(Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            oPesona = (Persona)Session["Usuario"];

            return View();
        }

        public ActionResult CerrarSesion()
        {
            Session["Usuario"] = null;
            return RedirectToAction("Index", "Login");
        }

    }
}

ProyectoBiblioteca/Controllers/BibliotecaController.cs
using Newtonsoft.Json;
using ProyectoBiblioteca.Logica;
using ProyectoBiblioteca.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoBiblioteca.Controllers
{
    public class BibliotecaController : Controller
    {
        // GET: Biblioteca
        public ActionResult Libros()
        {
            return View();
        }

        public ActionResult Autores()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListarAutor()
        {
            List<Autor> oLista = new List<Autor>();
            oLista = AutorLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarAutor(Autor objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdAutor == 0) ? AutorLogica.Instancia.Registrar(objeto) : AutorLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarAutor(int id)
        {
            bool respuesta = false;
            respuesta = AutorLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }



        [HttpGet]
        public JsonResult ListarLibro()
        {
            List<Libro> oLista = new List<Libro>();

            oLista = LibroLogica.Instancia.Listar();
           
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarLibro(string objeto, HttpPostedFileBase imagenArchivo)
        {

            Response oresponse = new Response() { resultado = true, mensaje = "" };

            try
            {
                Libro oLibro = new Libro();
                oLibro = JsonConvert.DeserializeObject<Libro>(objeto);


                if (oLibro.IdLibro == 0)
                {
                    int id = LibroLogica.Instancia.Registrar(oLibro);
                    oLibro.IdLibro = id;
                    oresponse.resultado = oLibro.IdLibro == 0 ? false : true;
                }
                else
                {
                    oresponse.resultado = LibroLogica.Instancia.Modificar(oLibro);
                }
            }
            catch (Exception e)
            {
                oresponse.resultado = false;
                oresponse.mensaje = e.Message;
            }

            return Json(oresponse, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarLibro(int id)
        {
            bool respuesta = false;
            respuesta = LibroLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarTipoPersona()
        {
            List<TipoPersona> oLista = new List<TipoPersona>();
            oLista = TipoPersonaLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarPersona()
        {
            List<Persona> oLista = new List<Persona>();

            oLista = PersonaLogica.Instancia.Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarPersona(Persona objeto)
        {
            bool respuesta = false;
            objeto.Clave = objeto.Clave == null ? "" : objeto.Clave;
            respuesta = (objeto.IdPersona == 0) ? PersonaLogica.Instancia.Registrar(objeto) : PersonaLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarPersona(int id)
        {
            bool respuesta = false;
            respuesta = PersonaLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


    }
    public class Response
    {

        public bool resultado { get; set; }
        public string mensaje { get; set; }
    }
}

ProyectoBiblioteca/Controllers/LoginController.cs
using ProyectoBiblioteca.Logica;
using ProyectoBiblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoBiblioteca.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string correo, string clave)
        {

            Persona ousuario = PersonaLogica.Instancia.Listar().Where(u => u.Correo == correo && u.Clave == clave && u.oTipoPersona.IdTipoPersona != 3).FirstOrDefault();

            if (ousuario == null)
            {
                ViewBag.Error = "Usuario o contraseña no correcta";
                return View();
            }

            Session["Usuario"] = ousuario;

            return RedirectToAction("Index", "Admin");
        }
    }
}

ProyectoBiblioteca/Controllers/PersonaController.cs
using ProyectoBiblioteca.Logica;
using ProyectoBiblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoBiblioteca.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Usuarios()
        {
            return View();
        }

        public ActionResult Lectores()
        {
            return View();
        }

        
    }
}

ProyectoBiblioteca/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>
<!-- Content Row -->
<div class="row">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total Libros
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="div_libros">0</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-book fa-2x text-black-50"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

        $(document).ready(function () {

            jQuery.ajax({
                url: '@Url.Action("ListarLibro", "Biblioteca")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.data != null) {
                        $("#div_libros").text(data.data.length)

                    } else {
                        $("#div_libros").text("0");
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });
        })


    </script>
}

ProyectoBiblioteca/Views/Biblioteca/Autores.cshtml
@{
    ViewBag.Title = "Autores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Autores</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <button class="btn btn-success btn-sm" type="button" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered" id="tabla" style="width:100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Nombre</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="FormModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLabel">Autor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="txtid" type="hidden" value="0" />
                <form id="formNivel">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtdescripcion">Nombre:</label>
                                <input type="text" class="form-control" id="txtdescripcion" name="descripcion" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script>
        var tabladata;

        $(document).ready(function () {


                tabladata = $('#tabla').DataTable({
                    responsive:true,
                    "ajax": {
                        "url": '@Url.Action("ListarAutor", "Biblioteca")',
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "Descripcion" },
                        {
                            "data": "IdAutor", "render": function (data, type, row, meta) {

                                return $("<button>").addClass("btn btn-primary btn-editar btn-sm").append(
                                    $("<i>").addClass("fas fa-pen")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML
                                +
                                $("<button>").addClass("btn btn-danger btn-eliminar btn-sm ml-2").append(
                                    $("<i>").addClass("fas fa-trash")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML;

                            },
                            "orderable": false,
                            "searchable": false,
                            "width": "90px"
                        }

                    ],
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                    }
                });
        });



        $(document).on('click', '.btn-editar', function (event) {
            var json = $(this).data("informacion")

            abrirModal(json)
        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtdescripcion").val("");

            if (json != null) {

                $("#txtid").val(json.IdAutor);
                $("#txtdescripcion").val(json.Descripcion);
            }

            $('#FormModal').modal('show');
        }

        $(document).on('click', '.btn-eliminar', function (event) {
            var json = $(this).data("informacion")

            jQuery.ajax({
                url: '@Url.Action("EliminarAutor", "Biblioteca")',
                type: "POST",
                data: JSON.stringify({ id: json.IdAutor}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                    } else {
                        alert("No se pudo eliminar")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });
        });

        function Guardar() {
            var request = {
                objeto: {
                    IdAutor: $("#txtid").val(),
                    Descripcion: $("#txtdescripcion").val()
                }
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarAutor", "Biblioteca")',
                type: "POST",
                data: JSON.stringify(request),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                        $('#FormModal').modal('hide');
                    } else {
                        alert("No se pudo guardar los cambios")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });

        }

    </script>

}

ProyectoBiblioteca/Views/Biblioteca/Libros.cshtml
@{
    ViewBag.Title = "Libros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- DataTales Example -->
<div class="card-header py-3 bg-primary">
    <h6 class="m-0 font-weight-bold text-white">Lista de libros</h6>
</div>
<div class="card-body">
    <div class="row">
        <div class="col-sm-12">
            <button class="btn btn-success btn-sm" type="button" onclick="abrirModal(null)">Crear Nuevo</button>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-12">

            <div class="table-responsive">
                <table class="table table-bordered" id="tabla" style="width:100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Titulo</th>
                            <th>Autor</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Titulo</th>
                            <th>Autor</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

</div>
</div>



<!-- Modal -->
<div class="modal fade" id="FormModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLabel">Libro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="txtid" type="hidden" value="0" />
                <form id="formNivel">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="txttitulo">Titulo</label>
                                <input type="text" class="form-control" id="txttitulo" name="descripcion" autocomplete="off">
                            </div>
                            <div class="form-group">
                                <label for="cboautor">Autor</label>
                                <select id="cboautor" class="form-control"></select>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{

    <script>
        var tabladata;

        $(document).ready(function () {

            jQuery.ajax({
                url: '@Url.Action("ListarAutor", "Biblioteca")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $.each(data.data, function (index, value) {
                        $("<option>").attr({ "value": value.IdAutor }).text(value.Descripcion).appendTo("#cboautor");
                    });
                },
                error: function (error) {
                    console.log(error)
                }
            });

            tabladata = $('#tabla').DataTable({
                responsive:true,
                "ajax": {
                    "url": '@Url.Action("ListarLibro", "Biblioteca")',
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Titulo" },
                    {
                        "data": "oAutor", render: function (data) {
                            return data.Descripcion
                        }
                    },
                    {
                        "data": "IdLibro", "render": function (data, type, row, meta) {

                            return $("<button>").addClass("btn btn-primary btn-editar btn-sm").append(
                                $("<i>").addClass("fas fa-pen")
                            ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML
                            +
                            $("<button>").addClass("btn btn-danger btn-eliminar btn-sm ml-2").append(
                                $("<i>").addClass("fas fa-trash")
                            ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML;

                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"
                    }

                ],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                }
            });
        });



        $(document).on('click', '.btn-editar', function (event) {
            var json = $(this).data("informacion")

            abrirModal(json)
        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txttitulo").val("");
            $("#cboautor").val($("#cboautor option:first").val());

            if (json != null) {

                $("#txtid").val(json.IdLibro);
                $("#txttitulo").val(json.Titulo);
                $("#cboautor").val(json.oAutor.IdAutor);
            }

            $('#FormModal').modal('show');
        }

        $(document).on('click', '.btn-eliminar', function (event) {
            var json = $(this).data("informacion")

            jQuery.ajax({
                url: '@Url.Action("EliminarLibro", "Biblioteca")',
                type: "POST",
                data: JSON.stringify({ id: json.IdLibro}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                    } else {
                        alert("No se pudo eliminar")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });
        });

        function Guardar() {

            var objeto = {
                IdLibro: $("#txtid").val(),
                Titulo: $("#txttitulo").val(),
                oAutor: { IdAutor: $("#cboautor option:selected").val() }
            }

            var request = new FormData();
            request.append("objeto", JSON.stringify(objeto));

            jQuery.ajax({
                url: '@Url.Action("GuardarLibro", "Biblioteca")',
                type: "POST",
                data: request,
                processData: false,
                contentType : false,
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                        $('#FormModal').modal('hide');
                    } else {
                        alert("No se pudo guardar los cambios")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });

        }

        $.fn.inputFilter = function (inputFilter) {
            return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function () {
                if (inputFilter(this.value)) {
                    this.oldValue = this.value;
                    this.oldSelectionStart = this.selectionStart;
                    this.oldSelectionEnd = this.selectionEnd;
                } else if (this.hasOwnProperty("oldValue")) {
                    this.value = this.oldValue;
                    this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
                } else {
                    this.value = "";
                }
            });
        };



    </script>

}

ProyectoBiblioteca/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    <style>

        
    </style>
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row d-flex align-items-center justify-content-center">
                            <div class="col-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                                    </div>
                                    <form class="user" action="@Url.Action("Index","Login")" method="post" >
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" name="correo" placeholder="Email" value="Admin@gmail.com">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="clave" placeholder="Password" value="123">
                                        </div>
                                        <div class="form-group">
                                            @{if (ViewBag.Error != null)
                                                {
                                                    <div class="alert alert-danger" role="alert">
                                                        @ViewBag.Error
                                                    </div>
                                                }
                                            }
                                        </div>
                                        <button class="btn btn-primary btn-block btn-user" type="submit">Ingresar</button>

                                    </form>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>